In [4]:
import numpy as np
from numpy.linalg import inv
from skimage.measure import marching_cubes
from scipy.ndimage import gaussian_filter, zoom
from os.path import join
from os import listdir
import os
import json
import cv2

import meshio
import nibabel as nib
from reg_utils import get_affine
from pygff import GFF, save

Define file paths

In [19]:
WORKDIR = os.getcwd()
ANNOTATION_FOLDER = join(WORKDIR, "assets", "annotations")
ATLAS_NIFTI = join(WORKDIR, "atlas", "reference", "mouse_nii", "atlas.nii")
SAGITTAL_FOLDER = join(WORKDIR, "assets", "sagittal")
DORSAL_FOLDER = join(WORKDIR, "assets", "dorsal")
MESHES_AND_VOXELS_FOLDER = join(WORKDIR, "data")
ATLAS_FOLDER = join(WORKDIR, "atlas")
IMAGE_FILES = join(WORKDIR, "assets", "images", "nii-images")

Define some constants

In [6]:
dorsal_height = 1980-168
dorsal_width = 2480-1300
dorsal_ratio = float(dorsal_height)/float(dorsal_width)
sagittal_width = 2550-808
sagittal_height = 1617-483
sagittal_ratio = float(sagittal_width)/float(sagittal_height)

z_height = sagittal_height

Get Affine Matrix

In [23]:
from reg_utils import get_affine

AFFINE = get_affine()
INV_AFFINE = inv(AFFINE)

Create list of images to interpolate between

In [5]:
num_dorsal = len(listdir(DORSAL_FOLDER))
num_sagittal = len(listdir(SAGITTAL_FOLDER))

dorsal_depth = 590 / num_dorsal
sagittal_depth = 590 / num_sagittal

dorsal_images = [[]] * num_dorsal
sagittal_images = [[]] * num_sagittal

def get_index(filename):
    return int(filename.replace("mouse","").replace(".png",""))

In [6]:
for image in listdir(SAGITTAL_FOLDER):
    if (image.split('.')[1] != "png"):
        continue
    index = get_index(image)
    im = cv2.imread(join(SAGITTAL_FOLDER, image))
    im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)

    sagittal_im = im[483:1617, 808:2550]
    height = dorsal_width
    width = dorsal_height

    sagittal_im = cv2.resize(sagittal_im, (width, height), interpolation=cv2.INTER_AREA)
    sagittal_images[index] = sagittal_im

Create volume and fill with images

In [43]:
output_nifti = np.zeros((dorsal_width, dorsal_width, dorsal_height), dtype=np.uint8)

for z in range (272, 862):
    i = z - 272
    try:
        index = float(i) / sagittal_depth
        ind0 = int(np.floor(index))
        if (ind0 < 0):
            continue
        if (ind0 + 1 >= num_sagittal):
            break
        img0 = np.array(sagittal_images[ind0]).astype(float)
        img1 = np.array(sagittal_images[ind0 + 1]).astype(float)
        alpha = (float (i % int(np.round(sagittal_depth)))) / sagittal_depth
        additiveImg = np.add(img0 * (1.0 - alpha), img1 * alpha).astype(np.uint8)
        output_nifti[z] = additiveImg
    except:
        pass

Flip image along Z axis

In [44]:
output_nifti = output_nifti[::, ::, ::-1]

Check data type

In [45]:
print(output_nifti.dtype)

uint8


Save nifti image

In [46]:
affine = get_affine()

nifti_img = nib.Nifti1Image(output_nifti, affine=affine)
nib.save(nifti_img, "./atlas/reference/mouse_nii/atlas.nii")

Define Organ Class

In [15]:
class Organ:
    def __init__(self, name, numSlices, depth, dims, affine, volume, label) -> None:
        self.name = name
        self.numSlices = numSlices
        self.slices = [[]] * numSlices
        self.scale = 1.0
        self.depth = depth * self.scale
        self.affine = affine
        # offset: [offset_x, offset_y, offset_z]
        self.offset = {
            "x": 252, # 124, # OFFSET_X - 36 * 6, # 424.2
            "y": 173, # 45, # OFFSET_Y - 80 * 6, # 33
            "z": 385 # 50 # 65
        }
        imgSliceDims = (numSlices, dims[1], dims[2])
        self.imageSlices: np.ndarray = np.zeros(imgSliceDims, dtype=np.uint8)
        self.voxelCloud: np.ndarray = np.zeros(volume.shape, dtype=np.uint8)
        self.volume = volume
        self.label = label
    
    def appendOrganSlice(self, index, entity):
        for polygon in entity["annotationBlocks"][0]["annotations"]:
            polyPts = np.array(polygon["segments"][0].copy()).astype(int)
            for i, pt in enumerate(polyPts):
                polyPts[i] = [(self.scale * pt[1]) - self.offset['y'], (self.scale * pt[0]) - self.offset['x']]
            self.slices[index].append(polyPts)
            cv2.fillPoly(self.imageSlices[index], pts=[polyPts], color=(255, 255, 255))

    def constructVoxelMap(self, save=False):
        for z in range(self.voxelCloud.shape[0]):
            # i: voxel layer
            i = z - self.offset['z']
            index = float(i) / self.depth
            ind0 = int(np.floor(index))
            if (ind0 < 0):
                continue
            if (ind0 + 1 >= len(self.imageSlices)):
                break
            img0 = self.imageSlices[ind0]
            img1 = self.imageSlices[ind0 + 1]
            alpha = (float(i % int(np.round(self.depth)) ) ) / (self.depth)
            additiveImage = np.add(img0 *  (1.0 - alpha), img1 * alpha)
            self.voxelCloud[z][np.where(additiveImage > 100)] = 255
        
        self.customCalibration()
        # self.generateMesh(save)

        if (save):
            # img = nib.Nifti1Image(self.voxelCloud, self.affine)
            # nib.save(img, f"./exports/{self.name}.nii")
            # print(f"Saved {self.name} image at ./exports/{self.name}.nii")
            del self.imageSlices
            del self.slices
    
    def customCalibration(self):
        # self.voxelCloud = np.swapaxes(self.voxelCloud, 0, 1)
        # self.voxelCloud = self.voxelCloud[::-1,::-1,::-1]

        # smooth between slices
        self.voxelCloud = gaussian_filter(self.voxelCloud, 7).astype(np.uint8)
        self.volume[np.where(self.voxelCloud > 100)] = self.label
        
    def generateMesh(self, save=False):
        threshold = 50
        step_size = 3
        print("Getting mesh")
        vertices, faces, _, _ = marching_cubes(self.voxelCloud, level=threshold, step_size=step_size)
        self.vertices = vertices
        self.faces = faces
        if (save):
            self.saveMesh()

    def getMesh(self):
        return self.vertices, self.faces

    def saveMesh(self):
        mesh = meshio.Mesh(self.vertices, {"triangle": self.faces})
        meshio.write(f"./exports/{self.name}.obj", mesh, file_format="obj")


Define Atlas Class

In [22]:
class_dict = {
    "Stomach": {
        "index": 1,
        "color": (255, 0, 0, 255)
    },
    "Ileum": {
        "index": 2,
        "color": (0, 255, 0, 255)
    },
    "Jejunum": {
        "index": 3,
        "color": (0, 0, 255, 255)
    },
    "Liver": {
        "index": 4,
        "color": (255, 255, 0, 255)
    },
    "Duodenum": {
        "index": 5,
        "color": (255, 0, 255, 255)
    },
    "Colon": {
        "index": 6,
        "color": (0, 255, 255, 255)
    },
    "Cecum": {
        "index": 7,
        "color": (128, 255, 255, 255)
    },
    "Rectum": {
        "index": 8,
        "color": (255, 128, 255, 255)
    },
}

In [24]:
class Atlas:
    def __init__(self, annotationDirectory, calibrationAnnotation, save=False) -> None:
        # TODO: Get directory length
        self.calibration: float = None
        self.xOffset: int = None
        self.yOffset: int = None
        self.zOffset: int = None

        self.atlasDims: tuple = None
        self.segmentation: np.ndarray = None
        self.affine = None

        self.organs = {}

        self.annotationDirectory = annotationDirectory

        self.save = save

        # ct = nib.load("./assets/images/sample/CT_TS_HEUHR_In111_free_M1039_0h_220721-selfcal.nii")
        ct = nib.load(join("atlas", "reference", "mouse_nii", "atlas.nii"))

        annFiles = listdir(annotationDirectory)
        numSlices = 0
        for file in annFiles:
            annList = json.load(open(join(self.annotationDirectory, file)))
            numSlices += len(annList)

        self.calibrateDepth(calibrationAnnotation, numSlices)
        self.calibrateImgSize(ct)
        self.constructAtlasFromList(annFiles, numSlices)
        self.constructImgVoxels(save=save)
        self.finalizeSegmentation()

    def constructAtlasFromList(self, fileList, numSlices):
        if (self.calibration == None):
            print("Requires calibration")
            return
        # get number of slices
        labels = {}
        next_label = 1
        for file in fileList:
            path = join(self.annotationDirectory, file)
            if (path == self.calibrationFile):
                print("Calibration file. Skipping...")
                continue
            print(f"Reading file {file}")
            annotationList = json.load(open(path))
            for annotation in annotationList:
                fname = annotation["documents"][0]["name"]
                index = int(fname.split('.')[0].replace("rat",""))
                try:
                    for entity in annotation["annotation"]["annotationGroups"][0]["annotationEntities"]:
                        name = entity["name"]
                        try:
                            label = labels[name]
                        except(KeyError):
                            labels[name] = next_label
                            label = next_label
                            next_label += 1
                            print(label)
                        try:
                            organ = self.organs[name]
                        except(KeyError):
                            organ = Organ(name, 
                                            numSlices, 
                                            self.calibration, 
                                            self.atlasDims,
                                            self.affine,
                                            self.segmentation,
                                            label)
                            self.organs[name] = organ
                        organ.appendOrganSlice(index, entity)
                except:
                    print(annotation)
    
    def finalizeSegmentation(self):
        self.segmentation = np.swapaxes(self.segmentation, 0, 1)
        self.segmentation = self.segmentation[::-1,::-1,::-1]
        img = nib.Nifti1Image(self.segmentation, self.affine)
        nib.save(img, f"./exports/segmentation.nii")
        # save("./exports/segmentation.gff", self.segmentation)
        if (save):
            atlas_segff = GFF(self.segmentation)
            atlas_segff.info.set_class_dict(class_dict)
            atlas_segff.info.affine = AFFINE
            save(join(ATLAS_FOLDER, "reference", "full_res_organ_nii", "segmentation.segff"), atlas_segff)

    def calibrateDepth(self, calibrationAnnotation, numSlices):
        f = open(calibrationAnnotation)
        annotation = json.load(f)[0]
        body = annotation["annotation"]["annotationGroups"][0]["annotationEntities"][0]
        domain = []
        for point in body["annotationBlocks"][0]["annotations"][0]["segments"][0]:
            domain.append(point[1])
        minZ = min(domain)
        maxZ = max(domain)
        diff = maxZ - minZ
        self.calibration = 1.0 * float(diff) / float(numSlices)
        self.calibrationFile = calibrationAnnotation
        return self.calibration
    
    def calibrateImgSize(self, inputNifti):
        """
        Parameters:
            inputNifti: nibabel.nifti1.Nifti1Image
        """
        # TODO: use nifi image size to calibrate canvas size for voxelclouds
        shape = inputNifti.get_fdata().shape
        self.atlasDims = shape
        self.segmentation = np.zeros(shape, dtype=np.uint8)
        self.affine = get_affine() #inputNifti.affine
        print(self.affine, type(self.affine))
        pass

    def constructImgVoxels(self, save=False):
        for organName in self.organs:
            organ = None
            try:
                organ = self.organs[organName]
            except:
                continue
            if (organ != None):
                print(f"Constructing voxel map for {organName} with label {organ.label}")
                organ.constructVoxelMap(save)
                print(np.where(self.segmentation == organ.label))
                print("Done")



Create organ atlas

In [25]:
atlas = Atlas(ANNOTATION_FOLDER, join(ANNOTATION_FOLDER, "calibrate.json"), save=True)

[[ 0.16952001  0.          0.         21.58835983]
 [ 0.          0.16952001  0.         21.69745827]
 [ 0.          0.          0.168538   95.23029327]
 [ 0.          0.          0.          1.        ]] <class 'numpy.ndarray'>
Calibration file. Skipping...
Reading file fixed_annotations.json
1
2
3
4
5
6
7
8
Constructing voxel map for Stomach with label 1
(array([397, 397, 397, ..., 743, 743, 743], dtype=int64), array([629, 630, 630, ..., 720, 720, 720], dtype=int64), array([1020, 1020, 1021, ...,  892,  893,  894], dtype=int64))
Done
Constructing voxel map for Ileum with label 2
(array([403, 403, 403, ..., 577, 577, 577], dtype=int64), array([729, 729, 729, ..., 790, 790, 790], dtype=int64), array([1126, 1127, 1128, ..., 1151, 1152, 1153], dtype=int64))
Done
Constructing voxel map for Jejunum with label 3
(array([391, 391, 391, ..., 751, 751, 751], dtype=int64), array([585, 585, 585, ..., 414, 414, 414], dtype=int64), array([1099, 1100, 1101, ..., 1101, 1102, 1103], dtype=int64))
Don

In [13]:
def rescale_nifti(nifti_file, scale):
    image = nib.load(nifti_file)
    image_data = image.get_fdata()
    rescaled_data = zoom(image_data, scale, order=1)
    rescaled_image = nib.Nifti1Image(rescaled_data, AFFINE)
    del image
    del image_data
    return rescaled_image

SCALE_FACTOR = 0.3

In [10]:
rescaled_image = rescale_nifti(ATLAS_NIFTI, SCALE_FACTOR)
nib.save(rescaled_image, "./atlas/reference/mouse_nii/scaled_atlas.nii")


In [18]:
FLIPPED = join(WORKDIR, "exports")
for file in listdir(FLIPPED):
    scaled = join(FLIPPED, "scaled")
    os.makedirs(scaled, exist_ok=True)
    if (file.endswith(".nii")):
        rescaled_image = rescale_nifti(join(FLIPPED, file), SCALE_FACTOR)
        nib.save(rescaled_image, join(scaled, f"scaled_{file}"))
        segff = GFF(rescaled_image.get_fdata().astype(np.uint8))
        segff.info.set_class_dict(class_dict)
        segff.info.affine = AFFINE
        print(segff.info)
        save(join(scaled, f"scaled_segmentation.segff"),segff)

--- self.info --- 
Meta: {'Project info': {'ClassColors': '0 0 0 255|0 0 255 255|0 255 0 255|255 0 0 255|0 255 255 255|255 0 255 255|255 255 0 255|255 255 128 255|255 128 255 255', 'ClassIndices': '0|1|2|3|4|5|6|7|8', 'ClassNames': 'unclassified|Stomach|Ileum|Jejunum|Liver|Duodenum|Colon|Cecum|Rectum'}}
Affine: [[ 0.16952001  0.          0.         21.58835983]
 [ 0.          0.16952001  0.         21.69745827]
 [ 0.          0.          0.168538   95.23029327]
 [ 0.          0.          0.          1.        ]]
Voxel sizes: [1. 1. 1.]
Intensity scale: 1.0
Intensity offset: 0.0
Timepoints: Equidistant: True
Centers: [0]
Widths: [0]
Channels: Equidistant: True
Centers: [0]
Widths: [0]

